### ISSUE TITLE
Bus Parameters of Generator

### ISSUE THREAD

**Issue by reid-g** [ORNL/GridKit#2]
The `BusPV` depends on the parameter `Pg` for creation. Currently under the `BusData` does not contain `Pg`. This will need to be added or setup as separate input. However, the parameter generally comes from a generator. Then the parse will need to be updated for this as well.

**Comment by pelesh** [comment]
I think `BusPV` should neither have nor try to set parameter `Pg`. This is now responsibility of `GeneratorPV`.

Also, the residual evaluation seems to be incorrect:
```c++
template <class ScalarT, typename IdxT>
int BusPV<ScalarT, IdxT>::evaluateResidual()
{
    P() = Pg_;
    Q() = 0.0;
    return 0;
}
```
The residual `P()` should be initialized to zero here. The PV generator and other components should then add their contributions to `P()`. The `Pg_` parameter seems to be remnant of the PV bus model that had embedded generator in it.

**Comment by reid-g** [comment]
So then is the `BusPV` supposed to reset the residuals to `0` and the `GeneratorPV` supposed to add the `P_` value? Or is the generator supposed to be an assignment too?

**Comment by pelesh** [comment]
The system model is designed to loop over buses first and then over all components. Buses initialize residuals to zero and looping over components then computes the residuals. `BusPV` has voltage magnitude fixed, so it solves only equation for the voltage phase. The corresponding residual is the one for active power `P`.

What is slightly confusing in this implementation is that the output `Q` is computed together with residual(s). Here `Q` is the reactive power that `GeneratorPV` needs to provide in order to keep voltage magnitude at `V_`. It is a residual in a physical sense but in the computational context, it is simulation output.

**Comment by pelesh** [comment]
> So then is the `BusPV` supposed to reset the residuals to `0` and the `GeneratorPV` supposed to add the `P_` value? Or is the generator supposed to be an assignment too?

Yes, you are correct, `GeneratorPV` is supposed to add the `P_` value.
